# Generated by Django 5.0.6 on 2026-04-21 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_status', models.CharField(choices=[('none', 'Não iniciado'), ('intended', 'Pretendo inscrever'), ('registered_declared', 'Inscrito (auto-declarado)'), ('withdrawn', 'Desisti'), ('completed', 'Concluído')], default='none', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('alert_on_deadline', models.BooleanField(default=True)),
                ('alert_on_changes', models.BooleanField(default=True)),
                ('alert_on_draws', models.BooleanField(default=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='tournaments.tournamentedition')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_items', to='players.playerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='watchlist_w_user_id_a1cd8d_idx'), models.Index(fields=['edition'], name='watchlist_w_edition_58a589_idx')],
                'unique_together': {('user', 'edition')},
            },
        ),
    ]
