# Generated by Django 5.0.6 on 2026-04-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('confederation', 'Confederação'), ('federation', 'Federação'), ('platform', 'Plataforma'), ('club', 'Clube'), ('media', 'Mídia')], max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('state', models.CharField(blank=True, help_text='UF para federações estaduais', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['type'], name='sources_org_type_7d61db_idx'), models.Index(fields=['state'], name='sources_org_state_6aaf48_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('source_type', models.CharField(choices=[('html', 'HTML Scraping'), ('pdf', 'PDF Parsing'), ('json', 'JSON API'), ('manual', 'Manual')], max_length=20)),
                ('base_url', models.URLField()),
                ('connector_key', models.CharField(help_text='Key matching a connector class (e.g. fpt_public, cbt_regulation)', max_length=100)),
                ('fetch_schedule_cron', models.CharField(default='0 * * * *', help_text='Cron expression for scheduler', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('P0', 'Crítica'), ('P1', 'Alta'), ('P2', 'Média'), ('P3', 'Baixa')], default='P1', max_length=2)),
                ('legal_notes', models.TextField(blank=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='sources.organization')),
            ],
            options={
                'ordering': ['organization__name', 'source_name'],
                'indexes': [models.Index(fields=['enabled'], name='sources_dat_enabled_cc0525_idx'), models.Index(fields=['connector_key'], name='sources_dat_connect_377a14_idx')],
            },
        ),
    ]
