# Generated by Django 5.0.6 on 2026-04-21 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('deadline_days', models.JSONField(default=list, help_text='Days before close to notify, e.g. [7,2,0]')),
                ('changes_enabled', models.BooleanField(default=True)),
                ('draws_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('deadline', 'Prazo se aproximando'), ('change', 'Dados alterados'), ('draws', 'Chaves publicadas'), ('canceled', 'Cancelado'), ('other', 'Outro')], max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'E-mail'), ('push', 'Push')], default='in_app', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('read', 'Lido')], default='pending', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='tournaments.tournamentedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='alerts_aler_user_id_2d0f3b_idx'), models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx'), models.Index(fields=['kind'], name='alerts_aler_kind_d59ca6_idx'), models.Index(fields=['dedup_key'], name='alerts_aler_dedup_k_e7b0db_idx')],
            },
        ),
    ]
