# Generated by Django 5.0.6 on 2026-04-21 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxonomy', models.CharField(choices=[('fpt_class', 'FPT - Classe'), ('fpt_age', 'FPT - Idade'), ('cbt_age', 'CBT - Idade'), ('seniors', 'Seniors'), ('kids', 'Kids'), ('open', 'Open/Profissional')], max_length=30)),
                ('code', models.CharField(help_text='e.g. 4M1, 14M, 35+', max_length=50)),
                ('label_ptbr', models.CharField(max_length=120)),
                ('gender_scope', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('X', 'Mistas'), ('*', 'Qualquer')], default='*', max_length=2)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('class_level', models.PositiveIntegerField(blank=True, help_text='1..5 for FPT classes', null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['taxonomy', 'code'],
                'indexes': [models.Index(fields=['taxonomy'], name='players_pla_taxonom_68b6a6_idx'), models.Index(fields=['code'], name='players_pla_code_79c3d4_idx')],
                'unique_together': {('taxonomy', 'code', 'gender_scope')},
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=120)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('home_state', models.CharField(blank=True, max_length=2)),
                ('home_city', models.CharField(blank=True, max_length=120)),
                ('travel_radius_km', models.PositiveIntegerField(default=100)),
                ('competitive_level', models.CharField(choices=[('beginner', 'Principiante'), ('amateur', 'Amador'), ('federated', 'Federado'), ('youth', 'Juvenil'), ('pro', 'Profissional')], default='amateur', max_length=20)),
                ('dominant_hand', models.CharField(blank=True, choices=[('R', 'Destro'), ('L', 'Canhoto')], max_length=1)),
                ('tennis_class', models.CharField(blank=True, help_text='FPT class: 1,2,3,4,5,PR,PRO', max_length=10)),
                ('is_primary', models.BooleanField(default=True)),
                ('external_ids', models.JSONField(blank=True, default=dict, help_text='CBT id, ITF id, etc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('confidence', models.CharField(choices=[('declared', 'Auto-declarado'), ('verified', 'Verificado')], default='declared', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_categories', to='players.playercategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_categories', to='players.playerprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['user', 'is_primary'], name='players_pla_user_id_5a5a42_idx'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['home_state'], name='players_pla_home_st_1158a2_idx'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['competitive_level'], name='players_pla_competi_0e5ee0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerprofilecategory',
            unique_together={('profile', 'category')},
        ),
    ]
