# Generated by Django 5.0.6 on 2026-04-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(help_text='e.g. fpt_abertos, cbt_juvenil, fpt_seniors, cbt_kids', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to='sources.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
                'unique_together': {('organization', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(help_text='e.g. 2026.1', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('deprecated', 'Depreciada')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='eligibility.ruleset')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('ruleset', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RuleClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_type', models.CharField(choices=[('age', 'Idade'), ('class', 'Classe'), ('membership', 'Filiação'), ('ranking', 'Ranking'), ('gender', 'Gênero'), ('generic', 'Genérica')], max_length=20)),
                ('category_code', models.CharField(blank=True, help_text='Category this clause applies to, blank = all', max_length=50)),
                ('logic', models.JSONField(default=dict, help_text='Machine-readable logic, e.g. {"min_age":14,"max_age":14,"gender":"M"}')),
                ('human_text', models.TextField(blank=True)),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='eligibility.ruleversion')),
            ],
            options={
                'indexes': [models.Index(fields=['rule_version', 'category_code'], name='eligibility_rule_ve_a5fcff_idx'), models.Index(fields=['clause_type'], name='eligibility_clause__3408ae_idx')],
            },
        ),
    ]
