# Generated by Django 5.0.6 on 2026-04-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0002_tournamentrule_binding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tournamentrulebinding',
            new_name='eligibility_edition_0d75c4_idx',
            old_name='elig_trb_edition_primary_idx',
        ),
        migrations.AlterField(
            model_name='tournamentrulebinding',
            name='binding_reason',
            field=models.CharField(blank=True, help_text='e.g. "2026 season rules", "CBT infantojuvenil reg 2026"', max_length=200),
        ),
    ]
