# Generated by Django 5.0.6 on 2026-04-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_federationentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='federationentry',
            new_name='registratio_edition_11bcf8_idx',
            old_name='reg_fedentry_ed_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='federationentry',
            new_name='registratio_payment_222715_idx',
            old_name='reg_fedentry_pay_idx',
        ),
        migrations.RenameIndex(
            model_name='federationentry',
            new_name='registratio_edition_d8cfd2_idx',
            old_name='reg_fedentry_ed_src_idx',
        ),
        migrations.RenameIndex(
            model_name='tournamentregistration',
            new_name='registratio_edition_b4acfe_idx',
            old_name='reg_edition_withdrawn_idx',
        ),
        migrations.RenameIndex(
            model_name='tournamentregistration',
            new_name='registratio_profile_5a208e_idx',
            old_name='reg_profile_edition_idx',
        ),
        migrations.RenameIndex(
            model_name='tournamentregistration',
            new_name='registratio_payment_04d95e_idx',
            old_name='reg_payment_status_idx',
        ),
        migrations.AlterField(
            model_name='federationentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
