# Generated by Django 5.0.6 on 2026-04-26 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_user_id_c9be81_idx',
            old_name='billing_pay_user_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_status_b7739e_idx',
            old_name='billing_pay_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_asaas_p_3a00e8_idx',
            old_name='billing_pay_asaas_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='billing_sub_status_948046_idx',
            old_name='billing_sub_status_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='billing_sub_next_du_f5dd14_idx',
            old_name='billing_sub_next_due_idx',
        ),
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['asaas_subscription_id'], name='billing_sub_asaas_s_80c227_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', '-created_at'], name='billing_sub_user_id_1342f1_idx'),
        ),
    ]
