# Generated by Django 5.0.6 on 2026-04-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_coach_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachathlete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
