# Generated by Django 5.0.6 on 2026-04-21 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('players', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_name', models.CharField(max_length=300)),
                ('canonical_slug', models.SlugField(max_length=300, unique=True)),
                ('circuit', models.CharField(blank=True, help_text='e.g. Abertos, Interclubes, Infantojuvenil, Kids, Seniors', max_length=100)),
                ('modality', models.CharField(default='tennis', help_text='tennis, beach_tennis, padel, wheelchair', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='sources.organization')),
            ],
            options={
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_year', models.PositiveIntegerField(db_index=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('title', models.CharField(help_text='Title as captured from source', max_length=300)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('entry_open_at', models.DateTimeField(blank=True, null=True)),
                ('entry_close_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('unknown', 'Desconhecido'), ('announced', 'Anunciado'), ('open', 'Inscrições Abertas'), ('closing_soon', 'Encerrando em breve'), ('closed', 'Inscrições Encerradas'), ('draws_published', 'Chaves Publicadas'), ('in_progress', 'Em Andamento'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], db_index=True, default='unknown', max_length=25)),
                ('surface', models.CharField(choices=[('clay', 'Saibro'), ('hard', 'Rápida / Sintética'), ('grass', 'Grama'), ('sand', 'Areia'), ('carpet', 'Carpete'), ('unknown', 'Não informada')], default='unknown', max_length=15)),
                ('base_price_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_notes', models.CharField(blank=True, max_length=300)),
                ('official_source_url', models.URLField(blank=True, max_length=500)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('raw_content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('data_confidence', models.CharField(choices=[('low', 'Baixa'), ('med', 'Média'), ('high', 'Alta')], default='med', max_length=10)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='sources.datasource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_editions', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-start_date', '-entry_close_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Criado'), ('status_changed', 'Status alterado'), ('dates_changed', 'Datas alteradas'), ('deadline_changed', 'Prazo alterado'), ('price_changed', 'Valor alterado'), ('venue_changed', 'Local alterado'), ('categories_changed', 'Categorias alteradas'), ('canceled', 'Cancelado'), ('draws_published', 'Chaves publicadas'), ('other', 'Outro')], max_length=30)),
                ('field_changes', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events', to='ingestion.ingestionrun')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='tournaments.tournamentedition')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_category_text', models.CharField(max_length=200)),
                ('price_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('visibility_order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('normalized_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_categories', to='players.playercategory')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournamentedition')),
            ],
            options={
                'ordering': ['visibility_order', 'source_category_text'],
            },
        ),
        migrations.CreateModel(
            name='TournamentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('registration', 'Inscrição'), ('regulation', 'Regulamento'), ('results', 'Resultados'), ('draws', 'Chaves'), ('other', 'Outro')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('is_official', models.BooleanField(default=True)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tournaments.tournamentedition')),
            ],
            options={
                'ordering': ['link_type'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['state'], name='tournaments_state_21dc87_idx'), models.Index(fields=['city'], name='tournaments_city_056f1f_idx')],
                'unique_together': {('name', 'city', 'state')},
            },
        ),
        migrations.AddField(
            model_name='tournamentedition',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='tournaments.venue'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['organization'], name='tournaments_organiz_eaab22_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['modality'], name='tournaments_modalit_586c18_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['circuit'], name='tournaments_circuit_22bed0_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentchangeevent',
            index=models.Index(fields=['edition', '-detected_at'], name='tournaments_edition_79868b_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentchangeevent',
            index=models.Index(fields=['event_type'], name='tournaments_event_t_fc30a9_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentcategory',
            index=models.Index(fields=['edition'], name='tournaments_edition_ed55aa_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentcategory',
            index=models.Index(fields=['normalized_category'], name='tournaments_normali_acc2b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentlink',
            unique_together={('edition', 'link_type', 'url')},
        ),
        migrations.AddIndex(
            model_name='tournamentedition',
            index=models.Index(fields=['status', 'entry_close_at'], name='tournaments_status_33f0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentedition',
            index=models.Index(fields=['start_date'], name='tournaments_start_d_09b962_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentedition',
            index=models.Index(fields=['season_year'], name='tournaments_season__0d7d93_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentedition',
            index=models.Index(fields=['raw_content_hash'], name='tournaments_raw_con_c8860f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentedition',
            unique_together={('tournament', 'season_year', 'external_id')},
        ),
    ]
