# Generated by Django 5.0.6 on 2026-04-26 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('tournaments', '0004_tournamentedition_dedup_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tournamentedition',
            index=models.Index(fields=['dedup_fingerprint'], name='tournaments_dedup_f_ece981_idx'),
        ),
    ]
