# Generated by Django 5.0.6 on 2026-04-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Sucesso'), ('partial', 'Parcial'), ('failed', 'Falha')], default='running', max_length=15)),
                ('items_fetched', models.PositiveIntegerField(default=0)),
                ('items_created', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('changes_detected', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.CharField(blank=True, max_length=50)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='sources.datasource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('json', 'JSON'), ('text', 'Texto')], max_length=10)),
                ('source_url', models.URLField(max_length=500)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('content_excerpt', models.TextField(blank=True)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['data_source', '-started_at'], name='ingestion_i_data_so_90df84_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['status'], name='ingestion_i_status_735e16_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionartifact',
            index=models.Index(fields=['checksum'], name='ingestion_i_checksu_aba8d9_idx'),
        ),
    ]
